/* ============================================================
   Recreate tables for PbiQueryStress (PostgreSQL)
   ============================================================ */

/* ============================================================
   1) benchmark
   ============================================================ */
CREATE TABLE IF NOT EXISTS benchmark
(
    benchmark_id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(256),
    created_by          VARCHAR(256),
    connection_string   TEXT,
    number_iterations   INTEGER NOT NULL DEFAULT 1,
    number_threads      INTEGER NOT NULL DEFAULT 1,
    query_delay         INTEGER NOT NULL DEFAULT 0,
    run_options         TEXT,
    concurrency         INTEGER,

    CONSTRAINT pk_benchmark PRIMARY KEY (benchmark_id)
);

/* ============================================================
   2) query_template
   ============================================================ */
CREATE TABLE IF NOT EXISTS query_template
(
    query_id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    query_name      VARCHAR(256),
    dax_query       TEXT,
    benchmark_id    INTEGER NOT NULL,

    CONSTRAINT pk_query_template PRIMARY KEY (query_id)
);

/* ============================================================
   3) query_runtime
   ============================================================ */
CREATE TABLE IF NOT EXISTS query_runtime
(
    runtime_id                   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    query_id                     INTEGER,
    dax                          TEXT,

    start_time                   TIMESTAMP(7),
    end_time                     TIMESTAMP(7),
    runtime_ms                   DOUBLE PRECISION,

    pbi_workspace                VARCHAR(512),
    error                        TEXT,
    status                       VARCHAR(128),
    user_id                      VARCHAR(256),

    benchmark_name               VARCHAR(256),

    data_transfer_start_time     TIMESTAMP(7),
    data_transfer_end_time       TIMESTAMP(7),
    data_transfer_ms             DOUBLE PRECISION,

    benchmark_run_id             INTEGER,
    number_threads               INTEGER,
    number_iterations            INTEGER,
    benchmark_run_name           VARCHAR(256),

    concurrency                  INTEGER,
    thread_id                    VARCHAR(128),

    CONSTRAINT pk_query_runtime PRIMARY KEY (runtime_id)
);

/* ============================================================
   4) parameters
   ============================================================ */
CREATE TABLE IF NOT EXISTS parameters
(
    parameter_id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(256),
    mapping_column       VARCHAR(256),
    query                TEXT,
    "connectionString"   TEXT,
    data_type            VARCHAR(128),
    format               VARCHAR(128),
    report_expression    TEXT,
    param_value          TEXT,

    query_id             INTEGER,
    benchmark_id         INTEGER,
    benchmark_param      BOOLEAN NOT NULL DEFAULT FALSE,
    query_name           VARCHAR(256),

    CONSTRAINT pk_parameters PRIMARY KEY (parameter_id)
);

/* ============================================================
   5) arc_mrv_recon_target_data
   ============================================================ */
CREATE TABLE IF NOT EXISTS arc_mrv_recon_target_data
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    business_date    VARCHAR(64),
    local_value      TEXT,
    src_book_id      VARCHAR(256),
    source           VARCHAR(128),
    measure_name     VARCHAR(256),
    level_name       VARCHAR(256),
    run_id           VARCHAR(256),
    measure_value    DOUBLE PRECISION,
    benchmark_run_id DOUBLE PRECISION,

    CONSTRAINT pk_arc_mrv_recon_target_data PRIMARY KEY (id)
);
